### ISSUE TITLE
No config file for 1.19.2

### ISSUE THREAD

**Issue by 4zy1** [pajicadvance/enchantmentdisabler#2]

**Comment by pajicadvance** [comment]
To clarify, yes, you have to enter any world for the config to appear. I know it's not ideal and I'm looking to change it in the next update.

**Comment by pajicadvance** [comment]
After some thinking, unfortunately there's no way for me to get around this. The problem stems from the fact that my mod also has to list enchantments from other mods, not just vanilla. If I initialize the config the usual way in which most Fabric mods do, there's no guarantee that my mod will be initialized last, which it has to, because otherwise enchantments from other mods won't be picked up. The most guaranteed way for my mod's config to initialize after every other mod is to initialize the config on world load.
